### PR TITLE
rust: bump to Rust 1.8.0

### PR DESCRIPTION
**Pull request by cardoe**
Rust 1.8.0 release

Signed-off-by: Doug Goldstein cardoe@cardoe.com

### CODE REVIEW

**Comment by cardoe** [comment]
Initial commit/PR still needs to actually be compiled.

**Comment by posborne** [comment]
@cardoe @derekstraka Would be nice to see this opened against usptream (or 1.9.0) -- I can take a look if you guys are busy.  For me, at least, this particular changes is failing when trying to apply patches.

```
ERROR: Command Error: exit status: 1  Output:
Applying patch 0002-Target-add-default-target.json-path-libdir-rust-targ.patch
patching file src/librustc/session/config.rs
Hunk #1 succeeded at 36 (offset 1 line).
Hunk #2 succeeded at 731 (offset 20 lines).
patching file src/librustc/session/mod.rs
Hunk #1 succeeded at 439 (offset 10 lines).
patching file src/librustc_back/target/mod.rs
Hunk #1 FAILED at 49.
Hunk #2 succeeded at 455 (offset 89 lines).
Hunk #3 succeeded at 492 (offset 21 lines).
1 out of 3 hunks FAILED -- rejects in file src/librustc_back/target/mod.rs
Patch 0002-Target-add-default-target.json-path-libdir-rust-targ.patch does not apply (enforce with -f)
ERROR: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /opt/builds/.../build/tmp/work-shared/rust-1.8.0-r0/temp/log.do_patch.10974
ERROR: Task 363 (/opt/builds/.../build/../sources/meta-rust/recipes-devtools/rust/rust-source.bb, do_patch) failed with exit code '1'
```

**Comment by cardoe** [comment]
Yeah all I did was take the existing work we did for getting 1.7.0 working and do the same manual moves for 1.8.0 and never attempt to compile it. I've been trying to get some fixes upstream that would do things differently and drop most of the patchset. Unfortunately I didn't get them to land for 1.10 so its probably best to get this done for 1.9.0 and hope that I land the series for 1.11 which will make future bumps much easier.

**Comment by posborne** [comment]
Sure, I'm fixing up patches right now and can submit something to upstream based on your commit if I get it all working today.  Thanks for all the work with usptream -- will be nice to get rid of the various hacks we have to do currently.

**Comment by cardoe** [comment]
The approach in these patches won't be supported upstream (when I say upstream I mean Rust). I'm changing all targets to JSON and changing how they are loaded.

**Comment by posborne** [comment]
> The approach in these patches won't be supported upstream (when I say upstream I mean Rust). I'm changing all targets to JSON and changing how they are loaded.

I'm on board and understand that the work will be temporary.  In my case, I just need something newer than 1.7.0 in the short term for an upcoming deadline.

**Comment by cardoe** [comment]
Sure I understand. I was just trying to clarify since I said upstream twice in my original comment and once meant meta-rust and once meant Rust.

**Comment by derekstraka** [comment]
@posborne - I had some WIP stuff on 186e215dcf50d2b51201779fb7a010c7c23e30f4 that may be helpful

**Comment by posborne** [comment]
@derekstraka Thank you!  I had the same stuff by now minus the rust-llvm changes which were leading to some fun.

**Comment by cardoe** [comment]
Obviously this is out dated. Thanks @posborne and @derekstraka for your help.

**Pull request closed without merging**
